# Nav Menus
menu:
    主页: /
    归档: /archives/
    关于我: /about.html

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/AngryPowman']
    - ['/images/rss.svg', '/atom.xml']

favicon: /favicon.ico

# About
about_info:
    name: "愤怒的泡面"
    bio: "十年饮冰·难凉热血"
    avatar: "/images/avatar.png"


# Comment
# e.g disqus: seansun
disqus:
duoshuo: angrypowman

# Analytics
# google_analytics: UA-65933410-1
tencent_analytics: 27319631
 
# Copyright Infomation
startyear: 2017
