# Nav Menus
menu:
    主页: /
    归档: /archives/

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/AngryPowman']
    - ['/images/rss.svg', '/atom.xml']


favicon: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:
duoshuo: angrypowman

# Analytics
# google_analytics: UA-65933410-1
tencent_analytics: 27319631
 
# Copyright Infomation
startyear: 2017
